version: '3.8'

services:
  beat-scrobble-db:
    image: postgres:16
    container_name: beat-scrobble-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=beatscrobbledb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - beat-scrobble-net

  beat-scrobble-app:
    image: ghcr.io/saturnx-dev/beat-scrobble:latest
    container_name: beat-scrobble-app
    restart: always
    ports:
      - "4110:4110"
    environment:
      - BEAT_SCROBBLE_DATABASE_URL=postgres://postgres:secret@beat-scrobble-db:5432/beatscrobbledb?sslmode=disable
      - BEAT_SCROBBLE_ALLOWED_HOSTS=*
    depends_on:
      - beat-scrobble-db
    networks:
      - beat-scrobble-net

networks:
  beat-scrobble-net:
    driver: bridge
