name: Clear all caches

on:
  workflow_dispatch:

jobs:
  wipe-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Wipe all caches
        uses: MyAlbum/purge-cache@v1
